export interface Patient {
  id: string;
  name: string;
  age: number;
  gender: "Male" | "Female";
  diagnosis: string;
  department: string;
  status: "Stable" | "Critical" | "Recovering" | "Discharged";
  admittedOn: string;
  doctor: string;
  avatar: string;
}

export const patients: Patient[] = [
  {
    id: "P001",
    name: "James Anderson",
    age: 54,
    gender: "Male",
    diagnosis: "Hypertension",
    department: "Cardiology",
    status: "Stable",
    admittedOn: "2025-04-10",
    doctor: "Dr. Sarah Lee",
    avatar: "JA",
  },
  {
    id: "P002",
    name: "Emily Carter",
    age: 32,
    gender: "Female",
    diagnosis: "Diabetes Type 2",
    department: "Endocrinology",
    status: "Recovering",
    admittedOn: "2025-04-14",
    doctor: "Dr. Mark Chen",
    avatar: "EC",
  },
  {
    id: "P003",
    name: "Robert Kim",
    age: 67,
    gender: "Male",
    diagnosis: "Cardiac Arrest",
    department: "Cardiology",
    status: "Critical",
    admittedOn: "2025-04-20",
    doctor: "Dr. Sarah Lee",
    avatar: "RK",
  },
  {
    id: "P004",
    name: "Sophia Patel",
    age: 45,
    gender: "Female",
    diagnosis: "Migraine",
    department: "Neurology",
    status: "Stable",
    admittedOn: "2025-04-18",
    doctor: "Dr. Amy Ross",
    avatar: "SP",
  },
  {
    id: "P005",
    name: "David Nguyen",
    age: 38,
    gender: "Male",
    diagnosis: "Fractured Femur",
    department: "Orthopedics",
    status: "Recovering",
    admittedOn: "2025-04-12",
    doctor: "Dr. John Park",
    avatar: "DN",
  },
  {
    id: "P006",
    name: "Olivia Brown",
    age: 29,
    gender: "Female",
    diagnosis: "Asthma",
    department: "Respiratory",
    status: "Discharged",
    admittedOn: "2025-04-08",
    doctor: "Dr. Lisa Wong",
    avatar: "OB",
  },
  {
    id: "P007",
    name: "Michael Torres",
    age: 72,
    gender: "Male",
    diagnosis: "Parkinson's",
    department: "Neurology",
    status: "Stable",
    admittedOn: "2025-04-05",
    doctor: "Dr. Amy Ross",
    avatar: "MT",
  },
  {
    id: "P008",
    name: "Ava Wilson",
    age: 41,
    gender: "Female",
    diagnosis: "Breast Cancer",
    department: "Oncology",
    status: "Critical",
    admittedOn: "2025-04-22",
    doctor: "Dr. Tom Bell",
    avatar: "AW",
  },
  {
    id: "P009",
    name: "Ethan Moore",
    age: 55,
    gender: "Male",
    diagnosis: "Kidney Stones",
    department: "Urology",
    status: "Recovering",
    admittedOn: "2025-04-17",
    doctor: "Dr. Nina Shah",
    avatar: "EM",
  },
  {
    id: "P010",
    name: "Isabella Clark",
    age: 63,
    gender: "Female",
    diagnosis: "Osteoporosis",
    department: "Orthopedics",
    status: "Stable",
    admittedOn: "2025-04-11",
    doctor: "Dr. John Park",
    avatar: "IC",
  },
  {
    id: "P011",
    name: "Liam Johnson",
    age: 48,
    gender: "Male",
    diagnosis: "COPD",
    department: "Respiratory",
    status: "Critical",
    admittedOn: "2025-04-23",
    doctor: "Dr. Lisa Wong",
    avatar: "LJ",
  },
  {
    id: "P012",
    name: "Mia Davis",
    age: 35,
    gender: "Female",
    diagnosis: "Appendicitis",
    department: "Surgery",
    status: "Discharged",
    admittedOn: "2025-04-09",
    doctor: "Dr. Kevin Hart",
    avatar: "MD",
  },
];
